robot_ip: 192.168.0.88
ur_type: ur5e
reverse_port: 50001
script_sender_port: 50002
trajectory_port: 50003
controller_namespace: /left/controller_manager
robot_controller: cartesian_compliance_controller